# Generated by Django 5.2.4 on 2025-08-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
